/**
 * Encore Features tab searchable-settings entries.
 *
 * Part of the searchableSettings.ts domain-file split, mirroring the
 * settingsStore.ts / settingsMetadata.ts slice decomposition (see
 * settingsAnnotatorSlice.ts for that pattern).
 */

import type { SearchableSetting } from './searchableSettings';

export const ENCORE_SETTINGS: SearchableSetting[] = [
	{
		id: 'encore-usage-stats',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Usage & Stats',
		description:
			'Track queries, Auto Run sessions, coding activity, and view the Usage Dashboard with a configurable lookback window',
		keywords: [
			'usage',
			'stats',
			'analytics',
			'dashboard',
			'tracking',
			'wakatime',
			'lookback',
			'activity',
			'query',
			'coding',
			'metrics',
			'tokens',
			'cost',
		],
	},
	{
		id: 'encore-symphony',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Maestro Symphony',
		description:
			'Contribute to open source projects through curated repositories and playbook registries',
		keywords: [
			'symphony',
			'open source',
			'oss',
			'contribute',
			'repository',
			'registry',
			'registry sources',
			'sources',
			'playbook',
			'curated',
		],
	},
	{
		id: 'encore-cue',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Maestro Cue',
		description:
			'Event-driven automation (Beta) - trigger agent prompts on timers, file changes, agent completions, GitHub PRs/issues, and pending tasks',
		keywords: [
			'cue',
			'automation',
			'trigger',
			'event',
			'timer',
			'file watch',
			'watcher',
			'pipeline',
			'global cue settings',
			'global settings',
			'subscription',
			'github',
			'pr',
			'issue',
			'beta',
			'cron',
			'schedule',
		],
	},
	{
		id: 'cue-history-retention',
		tab: 'encore',
		tabLabel: 'Encore Features',
		jumpToId: 'encore-cue',
		label: 'Cue history retention',
		description:
			"How many days of Maestro Cue run history to keep. The control is in the Cue modal's Activity Log header; runs older than the window are pruned when the Cue engine starts.",
		keywords: [
			'cue',
			'retention',
			'history',
			'activity log',
			'prune',
			'purge',
			'cleanup',
			'days',
			'keep',
			'database',
			'cue.db',
			'cue_events',
			'expire',
			'older than',
		],
	},
	{
		id: 'encore-coworking',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: 'Coworking',
		description:
			'Beta - let agents read terminal scrollback on demand. Installs a per-agent MCP server (Claude Code, Codex, OpenCode, Factory Droid) and adds a `term:N` pill to terminal tabs.',
		keywords: [
			'coworking',
			'mcp',
			'terminal',
			'scrollback',
			'agent',
			'tools',
			'claude code',
			'codex',
			'opencode',
			'factory droid',
			'beta',
			'install',
			'server',
		],
	},
	{
		id: 'coworking-background-browsers',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: 'Coworking background browsing',
		description:
			'Let agents read and drive their own browser tabs while you are focused on a different agent. Keeps hidden webviews alive off-screen, LRU-capped (1-10).',
		keywords: [
			'coworking',
			'background',
			'browser',
			'browsing',
			'webview',
			'hidden',
			'cross-session',
			'lru',
			'limit',
		],
	},
	{
		id: 'encore-director-notes',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: "Director's Notes",
		description: 'Unified history view and AI-generated synopsis across all sessions (Beta)',
		keywords: [
			'director',
			'notes',
			'synopsis',
			'synopsis provider',
			'provider',
			'history',
			'summary',
			'lookback',
			'beta',
			'fleet',
			'unified',
		],
	},
	{
		id: 'encore-director-notes-provider',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: "Synopsis Provider (Director's Notes)",
		description:
			'Use the first available provider, or pin the synopsis to one agent and customize it',
		keywords: [
			'director',
			'notes',
			'synopsis',
			'provider',
			'agent',
			'auto',
			'automatic',
			'first available',
			'claude',
			'codex',
			'opencode',
		],
	},
	{
		id: 'encore-director-notes-default-mode',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: "Director's Notes Default Reading Mode",
		description:
			'Whether the AI Overview opens in Rich (widget dashboard) or Plain (markdown) mode',
		keywords: [
			'director',
			'notes',
			'rich',
			'plain',
			'mode',
			'reading',
			'default',
			'dashboard',
			'widgets',
			'markdown',
		],
	},
	{
		id: 'encore-director-notes-ideal-end-state',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: "Ideal End State (Director's Notes)",
		description:
			'Describe the projects in flight and what done looks like; notes prioritize them and add a progress section',
		keywords: [
			'ideal',
			'end state',
			'goal',
			'target',
			'objective',
			'progress',
			'director',
			'notes',
			'projects',
			'roadmap',
		],
	},
	{
		id: 'encore-pianola',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Pianola',
		description:
			'Autonomous manager agent (Beta). Watches your agents, auto-answers low-risk prompts from your rules, and escalates uncertain or high-risk ones. Can send messages to agents on your behalf',
		keywords: [
			'pianola',
			'autonomous',
			'manager',
			'agent',
			'watch',
			'auto-answer',
			'auto answer',
			'escalate',
			'rules',
			'supervise',
			'orchestrate',
			'beta',
		],
	},
	{
		id: 'encore-concerto',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Concerto',
		description:
			'Agents answer with something you can look at and click. Ask for a chessboard, a dashboard, a mockup, or a simulator and it opens as a real interactive view on the Concerto stage - a window you can center or float beside the chat. Cadenzas add small cards that stay on top of every app. Open it with its hotkey, the command palette, or the Left Bar menu',
		keywords: [
			'concerto',
			'movement',
			'cadenza',
			'stage',
			'agent views',
			'views',
			'panel',
			'dashboard',
			'hud',
			'blockview',
			'data view',
			'visualize',
			'interactive',
			'game',
			'mockup',
			'simulator',
			'floating',
			'pop out',
		],
	},
	{
		id: 'encore-groups-plus',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Groups+',
		description:
			'Nested group folders with standard icons and label colors. Turn it on to organize the sidebar without changing stored group data.',
		keywords: [
			'groups',
			'groups plus',
			'folder',
			'nested',
			'hierarchy',
			'icon',
			'color',
			'sidebar',
			'organization',
		],
	},
	{
		id: 'encore-web-login',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Web Login',
		description:
			'Require a username and password on the web interface, manage the accounts on the tile, and attribute every turn to the person who sent it',
		keywords: [
			'web login',
			'login',
			'sign in',
			'sign out',
			'password',
			'account',
			'accounts',
			'user',
			'users',
			'username',
			'authentication',
			'auth',
			'attribution',
			'web interface',
			'remote control',
		],
	},
	{
		id: 'encore-plugins',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Plugins',
		description:
			'Community plugin subsystem (Alpha) - discover, enable, disable, install, and uninstall plugins. Foundation only: plugins are listed and managed but do not execute code yet',
		keywords: [
			'plugin',
			'plugins',
			'extension',
			'extend',
			'addon',
			'add-on',
			'community',
			'marketplace',
			'install',
			'uninstall',
			'alpha',
		],
	},
];
