/**
 * General tab searchable-settings entries.
 *
 * Part of the searchableSettings.ts domain-file split, mirroring the
 * settingsStore.ts / settingsMetadata.ts slice decomposition (see
 * settingsAnnotatorSlice.ts for that pattern).
 */

import { formatMetaKeyName } from '../../utils/shortcutFormatter';
import type { SearchableSetting } from './searchableSettings';

const META_KEY_NAME = formatMetaKeyName();

export const GENERAL_SETTINGS: SearchableSetting[] = [
	{
		id: 'general-conductor-profile',
		tab: 'general',
		tabLabel: 'General',
		label: 'Conductor Profile (About Me)',
		description: 'Tell agents about yourself so they know how to work with you',
		keywords: ['profile', 'about me', 'conductor', 'persona', 'bio'],
	},
	{
		id: 'general-global-show-hotkey',
		tab: 'general',
		tabLabel: 'General',
		label: 'Global Hotkey to Show Maestro',
		description: 'System-wide shortcut that summons the Maestro window from any app',
		keywords: [
			'hotkey',
			'global',
			'shortcut',
			'summon',
			'show',
			'focus',
			'foreground',
			'system-wide',
			'systemwide',
			'keyboard',
			'accelerator',
			'bring to front',
		],
	},
	{
		id: 'general-default-shell',
		tab: 'general',
		tabLabel: 'General',
		label: 'Default Terminal Shell',
		description:
			'Choose which shell to use for terminal sessions; configure custom shell path and arguments',
		keywords: [
			'shell',
			'bash',
			'zsh',
			'fish',
			'terminal',
			'powershell',
			'cmd',
			'pwsh',
			'path',
			'args',
			'arguments',
			'custom shell',
			'sh',
			'login shell',
		],
	},
	{
		id: 'general-log-level',
		tab: 'general',
		tabLabel: 'General',
		label: 'System Log Level',
		description: 'Higher levels show fewer logs. Debug shows all logs, Error shows only errors',
		keywords: ['log', 'debug', 'info', 'warn', 'error', 'verbosity', 'logging'],
	},
	{
		id: 'general-gh-path',
		tab: 'general',
		tabLabel: 'General',
		label: 'GitHub CLI (gh) Path',
		description: 'Specify the full path to the gh binary for Auto Run worktree features',
		keywords: ['github', 'gh', 'cli', 'git', 'path', 'worktree', 'binary'],
	},
	{
		id: 'general-maestro-cli',
		tab: 'general',
		tabLabel: 'General',
		label: 'Maestro CLI',
		description: 'Check PATH/version and install or update maestro-cli for the current user',
		keywords: ['maestro-cli', 'cli', 'path', 'version', 'install', 'update'],
	},
	{
		id: 'general-web-interface-auto-start',
		tab: 'general',
		tabLabel: 'General',
		label: 'Web Interface',
		description: 'Turn on the full browser interface automatically when Maestro opens',
		keywords: [
			'web ui',
			'web interface',
			'browser',
			'online',
			'offline',
			'live',
			'launch',
			'startup',
			'autostart',
			'remote control',
		],
	},
	{
		id: 'general-input-behavior',
		tab: 'general',
		tabLabel: 'General',
		label: 'Input Send Behavior',
		description:
			'Configure how to send messages (Enter or Cmd+Enter), AI Interaction Mode, the Expanded Prompt Composer (Shift+Enter), and Forced Parallel Execution',
		keywords: [
			'enter',
			'send',
			'input',
			'submit',
			'keyboard',
			'newline',
			'parallel',
			'forced parallel execution',
			'busy',
			'concurrent',
			'shift',
			'shift+enter',
			'composer',
			'prompt composer',
			'expanded composer',
			'mode',
			'ai interaction mode',
			'cmd+enter',
			'always force send',
			'send trigger',
			'modifier',
		],
	},
	{
		id: 'general-cross-agent-mentions',
		tab: 'general',
		tabLabel: 'General',
		label: 'Cross-Agent Mentions',
		description:
			'Control whether an @-mention is a consult (read-only, default) or a delegation (the agent may write files)',
		keywords: [
			'cross-agent',
			'cross agent',
			'mention',
			'@mention',
			'@-mention',
			'consult',
			'delegate',
			'delegation',
			'read-only',
			'readonly',
			'read only',
			'write',
			'read-write',
			'writable',
			'permission',
			'agent to agent',
		],
	},
	{
		id: 'general-autorun-inactivity-timeout',
		tab: 'general',
		tabLabel: 'General',
		label: 'Auto Run Inactivity Timeout',
		description:
			'Auto Run force-kills a task if the agent produces no output for this many minutes - useful for long refactors, heavy test runs, or web-research tasks',
		keywords: [
			'autorun',
			'auto run',
			'inactivity',
			'timeout',
			'stalled',
			'minutes',
			'watchdog',
			'kill',
			'refactor',
			'test',
			'research',
			'long running',
		],
	},
	{
		id: 'general-autorun-max-task-duration',
		tab: 'general',
		tabLabel: 'General',
		label: 'Auto Run Max Task Duration',
		description:
			'Absolute cap on how long a single Auto Run task may run regardless of output. Catches a stuck-but-chatty agent that keeps emitting yet never finishes and would otherwise hang the whole run',
		keywords: [
			'autorun',
			'auto run',
			'max',
			'maximum',
			'duration',
			'timeout',
			'cap',
			'minutes',
			'watchdog',
			'kill',
			'hang',
			'stuck',
			'long running',
		],
	},
	{
		id: 'general-history',
		tab: 'general',
		tabLabel: 'General',
		label: 'Default History Toggle',
		description:
			'Enable "History" by default for new tabs, saving a synopsis after each completion',
		keywords: ['history', 'synopsis', 'save', 'toggle'],
	},
	{
		id: 'general-group-cue-entries',
		tab: 'general',
		tabLabel: 'General',
		label: 'Group Cue History Entries',
		description:
			'Collapse repeated Cue runs into one History row with a run count, the most recent run time, and a failure count',
		keywords: [
			'cue',
			'group',
			'grouping',
			'collapse',
			'collapsed',
			'history',
			'entries',
			'rows',
			'repeated',
			'duplicate',
			'noise',
			'trigger',
			'run count',
			'automation',
		],
	},
	{
		id: 'general-synopsis-debounce',
		tab: 'general',
		tabLabel: 'General',
		label: 'Synopsis Debounce',
		description:
			'Idle time to wait before generating a History synopsis; coalesces rapid completions into one',
		keywords: ['synopsis', 'debounce', 'coalesce', 'history', 'delay', 'throttle', 'idle'],
	},
	{
		id: 'general-thinking-mode',
		tab: 'general',
		tabLabel: 'General',
		label: 'Default Thinking Mode',
		description:
			'Show AI thinking/reasoning content for new tabs - Off, On, or Sticky. Off shows only final responses.',
		keywords: [
			'thinking',
			'reasoning',
			'chain of thought',
			'streaming',
			'sticky',
			'off',
			'on',
			'response',
			'final',
		],
	},
	{
		id: 'general-tool-calls',
		tab: 'general',
		tabLabel: 'General',
		label: 'Tool Calls',
		description:
			'Show or hide tool-call activity (tool badges and their input/output) in AI responses.',
		keywords: [
			'tool',
			'tools',
			'tool call',
			'tool calls',
			'tool activity',
			'badge',
			'wrench',
			'hide',
			'show',
			'function call',
		],
	},
	{
		id: 'general-tab-behavior',
		tab: 'general',
		tabLabel: 'General',
		label: 'Tab Behavior',
		description: 'Automatic tab naming and where new tabs are placed in the tab bar',
		keywords: [
			'tab',
			'name',
			'naming',
			'auto',
			'rename',
			'title',
			'placement',
			'new tab',
			'new browser',
			'browser tab',
			'new terminal',
			'opened file',
			'file tab',
			'terminal tab',
			'position',
			'order',
			'right',
			'end',
		],
	},
	{
		id: 'general-utility-agent',
		tab: 'general',
		tabLabel: 'General',
		label: 'Utility Agent',
		description:
			'Route auxiliary tasks (tab naming, context grooming) to a cheaper or faster agent with an optional model override',
		keywords: [
			'utility',
			'auxiliary',
			'agent',
			'model',
			'tab naming',
			'context grooming',
			'grooming',
			'cheaper',
			'faster',
			'background',
			'haiku',
			'override',
		],
	},
	{
		id: 'general-spell-check',
		tab: 'general',
		tabLabel: 'General',
		label: 'Enable spell checking',
		description:
			'Show spell check suggestions in input areas (prompt input, group chat, file editor). Disabled by default.',
		keywords: [
			'spell',
			'spell check',
			'spelling',
			'spellcheck',
			'dictionary',
			'autocorrect',
			'suggestions',
			'typo',
			'red underline',
			'input',
			'prompt input',
			'group chat',
			'file editor',
		],
	},
	{
		id: 'general-power',
		tab: 'general',
		tabLabel: 'General',
		label: 'Prevent Sleep While Working',
		description:
			'Keeps your computer awake when AI agents are busy, Auto Run is active, or Cue pipelines are scheduled',
		keywords: [
			'sleep',
			'power',
			'awake',
			'prevent sleep',
			'caffeine',
			'battery',
			'cue',
			'pipeline',
			'idle',
			'wake',
		],
	},
	{
		id: 'general-display-sleep',
		tab: 'general',
		tabLabel: 'General',
		label: 'Keep the Display Awake',
		description:
			'Blocks the screen saver, screen lock, and idle logout while agents work. Pauses macOS background maintenance.',
		keywords: [
			'display',
			'screen',
			'screen saver',
			'screensaver',
			'lock',
			'screen lock',
			'logout',
			'monitor',
			'awake',
			'power',
			'caffeinate',
			'maintenance',
			'spotlight',
		],
	},
	{
		id: 'general-rendering',
		tab: 'general',
		tabLabel: 'General',
		label: 'Rendering Options',
		description: 'GPU acceleration and confetti animations',
		keywords: ['gpu', 'rendering', 'acceleration', 'confetti', 'animation', 'hardware'],
	},
	{
		id: 'general-auto-resume',
		tab: 'general',
		tabLabel: 'General',
		label: 'Resume Paused Sessions on Limit',
		description:
			'Automatically resume agents that paused on a token, API, or credit limit once the provider window reopens',
		keywords: [
			'resume',
			'limit',
			'credit',
			'token',
			'rate limit',
			'quota',
			'auto resume',
			'exhaustion',
			'paused',
		],
	},
	{
		id: 'general-auto-resume-interval',
		tab: 'general',
		tabLabel: 'General',
		label: 'Auto-Resume Check Interval',
		description:
			'How often to probe for credit/limit availability before resuming paused agents, and how long to keep trying before giving up',
		keywords: [
			'resume',
			'limit',
			'credit',
			'token',
			'rate limit',
			'quota',
			'auto resume',
			'exhaustion',
			'paused',
			'interval',
			'give up',
		],
	},
	{
		id: 'general-updates',
		tab: 'general',
		tabLabel: 'General',
		label: 'Check for Updates on Startup',
		description: 'Automatically check for new Maestro versions when the app starts',
		keywords: ['update', 'check', 'startup', 'version', 'auto update'],
	},
	{
		id: 'general-beta-updates',
		tab: 'general',
		tabLabel: 'General',
		label: 'Pre-release Channel',
		description: 'Include beta and release candidate updates',
		keywords: ['beta', 'pre-release', 'rc', 'release candidate', 'canary'],
	},
	{
		id: 'general-crash-reporting',
		tab: 'general',
		tabLabel: 'General',
		label: 'Send Anonymous Crash Reports',
		description: 'Help improve Maestro by automatically sending crash reports',
		keywords: ['crash', 'reporting', 'privacy', 'telemetry', 'sentry', 'anonymous'],
	},
	{
		id: 'general-browser',
		tab: 'general',
		tabLabel: 'General',
		label: 'Default Browser',
		description: `Choose whether links open in the Maestro built-in browser tab or the system browser. ${META_KEY_NAME}+click (or right-click context menu) inverts the behavior. Set the default URL for new browser tabs.`,
		keywords: [
			'browser',
			'links',
			'external',
			'system',
			'internal',
			'url',
			'open',
			'ctrl',
			'ctrl+click',
			'ctrl-click',
			'cmd',
			'cmd+click',
			'command+click',
			'right click',
			'context menu',
			'home',
			'homepage',
			'default',
			'leaderboard',
			'webview',
		],
	},
	{
		id: 'general-html-double-click',
		tab: 'general',
		tabLabel: 'General',
		label: 'Open HTML files in Maestro Browser on double-click',
		description:
			'When enabled, double-clicking an HTML file in the file explorer opens it in the Maestro browser tab instead of the file preview.',
		keywords: [
			'html',
			'double click',
			'double-click',
			'dblclick',
			'file explorer',
			'preview',
			'browser',
			'open',
			'render',
			'webview',
			'dashboard',
		],
	},
	{
		id: 'general-browser-keepalive',
		tab: 'general',
		tabLabel: 'General',
		label: 'Background browser tabs',
		description:
			'Control whether inactive browser tabs are unloaded (reloading on return) or kept alive to preserve their in-memory state. Keep the most-recent N tabs alive or keep them all alive.',
		keywords: [
			'browser',
			'background',
			'tab',
			'keep alive',
			'keepalive',
			'keep-alive',
			'unload',
			'reload',
			'webview',
			'memory',
			'persist',
			'persistence',
			'state',
			'suspend',
			'lru',
			'recent',
			'inactive',
		],
	},
	{
		id: 'general-storage',
		tab: 'general',
		tabLabel: 'General',
		label: 'Storage Location',
		description:
			'Choose where Maestro stores settings, sessions, groups, agents, global environment variables, and configuration. Use a synced folder (iCloud Drive, Dropbox, OneDrive) to share across devices. Migrating may require a restart.',
		keywords: [
			'storage',
			'sync',
			'icloud',
			'icloud drive',
			'dropbox',
			'onedrive',
			'folder',
			'path',
			'location',
			'agents',
			'environment variables',
			'configuration',
			'migrate',
			'migration',
			'restart',
			'devices',
			'share',
		],
	},
];
