/**
 * Social preview (Open Graph / Twitter card) tags for the web-desktop page.
 *
 * A web-desktop URL is shared in a chat app far more often than it is typed:
 * someone opens Maestro on their desktop and sends themselves the link. Those
 * clients render whatever the page declares, and with nothing declared the card
 * collapses to the page title over a bare LAN address - which reads like a
 * misconfigured router rather than an invitation into a workspace.
 *
 * Two rules this module exists to hold:
 *
 * 1. **Every URL in the card is absolute.** `og:image` and `og:url` are resolved
 *    by the crawler against nothing at all, so a relative path is simply
 *    dropped. The origin is derived per request rather than stored, because the
 *    same server answers on a LAN IP, on `localhost`, and through a tunnel, and
 *    each of those has to describe itself with the host the sharer actually used.
 * 2. **The card carries no session data.** It is a brand mark, and a link
 *    preview is generated by whichever device the message passes through. A card
 *    naming agents or paths would leak that workspace into a chat transcript,
 *    an image cache, and a crawler's logs.
 */

/**
 * Where the preview image is served from.
 *
 * Deliberately OUTSIDE the token prefix, unlike every other asset. A crawler
 * that already has the page URL has the token anyway, so this buys no secrecy -
 * what it buys is that the image survives being fetched by a client that
 * rewrites or strips the path, and that the token is absent from an image URL
 * which chat clients cache and re-host. The file is a static brand mark with
 * nothing user-specific in it, so serving it unauthenticated costs nothing.
 */
export const OG_IMAGE_ROUTE = '/og.png';

/** Card dimensions, restated for the crawler so it can lay out before the fetch. */
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * The product name, with no qualifier.
 *
 * "Maestro (Web Desktop)" named the BUILD rather than the product: the
 * parenthetical is an internal distinction between two bundles of the same app,
 * and it surfaced in every shared link and browser tab as though the recipient
 * were being handed a variant.
 */
export const SOCIAL_TITLE = 'Maestro';

export const SOCIAL_DESCRIPTION =
	'Your Maestro workspace, live in the browser. Every agent, every tab, from any device on your network.';

/** Escape a value for an HTML attribute in a double-quoted context. */
function escapeAttribute(value: string): string {
	return value
		.replace(/&/g, '&amp;')
		.replace(/"/g, '&quot;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;');
}

/**
 * Resolve the origin a crawler should be pointed back at.
 *
 * `x-forwarded-proto` wins when present: the server itself only ever speaks
 * HTTP, so when Maestro is reached through a tunnel (Tailscale Serve,
 * cloudflared, a reverse proxy) the scheme it can see locally is the wrong one,
 * and an `http://` image URL on an `https://` page is blocked as mixed content -
 * the card renders with a hole where the image should be.
 *
 * Returns null when the request carries no host - including when it carries no
 * headers at all. A card built on a guessed host points every crawler at an
 * address that is not the one being shared, so no card is the better failure:
 * the page still loads and the preview falls back to the title.
 */
export function resolveRequestOrigin(
	headers: Record<string, unknown> | null | undefined
): string | null {
	if (!headers) return null;

	const rawHost = headers['x-forwarded-host'] ?? headers['host'];
	const host = Array.isArray(rawHost) ? rawHost[0] : rawHost;
	if (typeof host !== 'string' || host.trim() === '') return null;

	const rawProto = headers['x-forwarded-proto'];
	const forwarded = Array.isArray(rawProto) ? rawProto[0] : rawProto;
	// A proxy chain sends a comma-separated list; the first entry is the client.
	const proto =
		typeof forwarded === 'string' && forwarded.trim() !== ''
			? forwarded.split(',')[0].trim().toLowerCase()
			: 'http';

	// Anything other than the two schemes a browser will follow is a header a
	// caller controls, so it is not passed through into a URL we emit.
	const scheme = proto === 'https' ? 'https' : 'http';
	return `${scheme}://${host.trim()}`;
}

/**
 * Build the `<meta>` block for the page served at `origin`.
 *
 * Both vocabularies are emitted. Open Graph is what iMessage, Slack, Signal,
 * Discord and WhatsApp read; `twitter:card` is what tells clients following
 * Twitter's spec to use the LARGE image rather than the small thumbnail beside
 * the text, which is the difference between a card that looks designed and one
 * that looks like a favicon fell into a chat bubble.
 */
export function buildSocialPreviewTags(origin: string): string {
	const imageUrl = `${origin}${OG_IMAGE_ROUTE}`;
	const attr = escapeAttribute;

	return [
		`<meta property="og:type" content="website" />`,
		`<meta property="og:site_name" content="${attr(SOCIAL_TITLE)}" />`,
		`<meta property="og:title" content="${attr(SOCIAL_TITLE)}" />`,
		`<meta property="og:description" content="${attr(SOCIAL_DESCRIPTION)}" />`,
		`<meta property="og:url" content="${attr(origin)}" />`,
		`<meta property="og:image" content="${attr(imageUrl)}" />`,
		`<meta property="og:image:type" content="image/png" />`,
		`<meta property="og:image:width" content="${OG_IMAGE_WIDTH}" />`,
		`<meta property="og:image:height" content="${OG_IMAGE_HEIGHT}" />`,
		// Named for screen readers and for clients that show alt text while the
		// image loads over a slow link.
		`<meta property="og:image:alt" content="${attr(`${SOCIAL_TITLE} - your agent workspace, in the browser`)}" />`,
		`<meta name="twitter:card" content="summary_large_image" />`,
		`<meta name="twitter:title" content="${attr(SOCIAL_TITLE)}" />`,
		`<meta name="twitter:description" content="${attr(SOCIAL_DESCRIPTION)}" />`,
		`<meta name="twitter:image" content="${attr(imageUrl)}" />`,
		// Plain description too. Some clients (and every search crawler) read this
		// one and never look at Open Graph.
		`<meta name="description" content="${attr(SOCIAL_DESCRIPTION)}" />`,
	].join('');
}
